### ISSUE TITLE
Tried Example - error object 'C_map_type' not found

### ISSUE THREAD

**Issue by wmatwijec** [FilipeamTeixeira/skynet#1]
Tried example and got this error.   igraph package is loaded

> network <- make.netDir(OD_Sample)
> netMap(network$netDir, pct = 10)
Error in maptype(database) : object 'C_map_type' not found

**Comment by FilipeamTeixeira** [comment]
Unfortunately I can't replicate it in several systems.
- If you type `?map`, without the ``, do you see more than one package using that function? If you do, can you try to unload the other package causing the conflict?
- As an alternative, can you load skynet on a fresh R session and see if this works there?

From what I've seen online, someone complained about this as well here https://github.com/adeckmyn/maps/issues/9, but it was related to a bad maps package version.

Please keep me updated.

**Comment by wmatwijec** [comment]
I reinstalled maps from CRAN and the issue cleared.  Thanks for this effort on your part.
